### ISSUE TITLE
Download scale - size of downloadable data files

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#29] opened 2019-01-15 14:31 UTC
To determine the maximal size of a data file to be downloadable on the portal that makes sense for a user and that does not break the portal.

**Comment by dvdkamp** [comment] 2019-01-18 16:00
I'm wondering, if I should be assigned to this as I will be on leave for the entire sprint?

**Comment by tomLandry** [comment] 2019-01-18 16:14
Oh, right. I forgot. Well you did provide your input though, so in a sense you already pulled the task in the "In Progress" column. Someone can take it from there.

**Comment by tomLandry** [comment] 2019-01-23 15:04
@tomkralidis as discussed, this should be planned ahead. Get a better idea quickly on thoughput, use cases to estimate the volumetry.

**Comment by tomkralidis** [comment] 2019-01-23 15:47
We can also investigate chunking downloads as we have done on the [CCCS climate data extraction tool](https://climate-change.canada.ca/climate-data/#/cmip5-data) as a strategy to provide meaningful downloads without straining infrastructure too much.

**Comment by dbyrns** [comment] 2019-02-13 16:31
Question for the product vision group : What is the expectation for the size / qty of files to be downloadable. I already performed a small test showing that we can download a 60Go file from thredds in 15 minutes. If we have a better idea of the expectations we can set in place a test to validate them.

**Comment by dbyrns** [comment] 2019-02-13 20:05
Also I would like to know, if we intend to download a whole dataset (multiple files) how are we expecting to do that? Because if we want to zip them it will require a zipping process and could be pretty time/resource consuming. Other options would be to download multiple files or give file urls. Moreover if we intend to download a subset spreads over multiple files that will require some processing and temporary files I guess. Then the issue is no more file download only, it become a processing issue too.

**Comment by dvdkamp** [comment] 2019-02-19 15:34
@dbyrns, @tomLandry, @MarcAndreDubuc, I've provided some comments/questions in issue #6 that pertain to this issue

**Comment by rod-glover** [comment] 2019-02-20 22:01
@dbyrns In response to zipping, we recommend that you do not do this. That's unnecessary and in some ways undesirable. @huard has provided and idea for delivering collections (multiple files) that I elaborated on in https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/6.

**Comment by tomLandry** [comment] 2019-02-22 13:32
I think we made good strides at our last Architecture meeting and that mutual understanding is quite good. We would be ready to put what we know as specs for the portal to follow, and to size hardware requirements of CRIM's infrastructure. @dbyrns is a great "synthetizer" for that type of things. There are of course outstanding questions, but they're either not critical/blocker, or they could wait for next sprint (or next week in new issue). Added https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/55 as one of the major issues.

**Comment by dbyrns** [comment] 2019-02-22 15:41
Ok following the last AWG meeting, we have agreed on the plan described here : https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/64520247/Architecture#Architecture-DownloadSubsetData
Since we know that THREDDS offers direct download and handle the largest file (60Go) pretty well : https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/63373627/Data+transfer+tests
And that we have now a separate issue for OpenDAP access : https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/55
We can clause this one.

**Comment by tomLandry** [comment] 2019-02-22 15:43
Annnnnnnd I validate the issue, then putting it in "done".

**Closed** 2019-02-22 15:42 UTC
Labels: F.D- Analyze, Priority - Blocker, WG- Architecture, WG- Data, WG- Product Vision
